### ISSUE TITLE
New project from EXF template fails to build in Visual Studio

### ISSUE THREAD

**Issue by willsam100** [fsprojects/Elmish.XamarinForms#102]
**Error**:
`/Users/sam.williams/Projects/SqueakyApp/SqueakyApp/FSC: Error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'voption`1' (FS0193) (SqueakyApp)`

Occurs in all projects - Core, Droid and iOS 

**Expected**:
all projects build successfully

**Steps**:
dotnet new elmish-forms-app -lang F# -n SqueakyApp
create an sln file and add the three projects
open sln file in Visual Studio for Mac
build project (I used `DEBUG | AnyCPU` as the configuration) 

also tried changed FSharp.Core version in the .NET Standard project using both 4.3.4 and 4.5.0. The .NET Standard project still fails to build. 
also tried adding the fsc.props file

**Environment**:
```
=== Visual Studio Professional 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: 82dffde3-8fbe-456a-90d8-d8692da1f7d9
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.0
	2.0.5
	2.0.0
	1.1.2
	1.1.1
	1.1.0
	1.0.5
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.300/Sdks
SDK Versions:
	2.1.300
	2.1.4
	2.0.0
	1.0.4
	1.0.1
	1.0.0-preview2-1-003177
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Professional)
Android SDK: /Users/sam.williams/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		5.1   (API level 22)
		6.0   (API level 23)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.3.1 (14154.1)
Build 9E501

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Professional)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Professional)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Straight8's SpecFlow Intergration 1.11.0.0
Internet of Things (IoT) development (Preview) 7.5
```

**Comment by dsyme** [comment]
Could you link a build log?  e.g. using 

    msbuild SqueakyApp.sln /v:n

from the command line, thanks.  I suspect some problem with package restore

**Comment by willsam100** [comment]
Here is the log output from running `msbuild SqueakyApp.sln /v:n`
I can also attached a zip of the project if that is useful. 

[build.log](https://github.com/fsprojects/Elmish.XamarinForms/files/2168497/build.log)

**Comment by willsam100** [comment]
[SqueakyApp.zip](https://github.com/fsprojects/Elmish.XamarinForms/files/2168506/SqueakyApp.zip)
Here is a zip of the files for the project, if that helps. (Note that packages are not restored, as that would have been too large).

**Comment by dsyme** [comment]
This is  wrong, you definitely need 4.5.0 (though you said it doesn't compile if you change that?  I haven't tried yet, just searched for "4.3.4". Did you do a clean build after changing to 4.5.0?)
```
  <package id="FSharp.Core" version="4.3.4" targetFramework="xamarinios10" />
```

**Comment by dsyme** [comment]
And here: 
```
    <Reference Include="FSharp.Core">
      <HintPath>..\packages\FSharp.Core.4.3.4\lib\netstandard1.6\FSharp.Core.dll</HintPath>
    </Reference>
```

**Comment by dsyme** [comment]
Could you send a new build log with those changed to 4.5.0, and use `msbuild /v:d`, thanks

**Comment by nosami** [comment]
@willsam100 : ugh, yes - this is a known issue in VSMac and was recently fixed

**Comment by nosami** [comment]
https://github.com/mono/monodevelop/pull/5137
