### ISSUE TITLE
Project created with elmish-forms-app template fails to build

### ISSUE THREAD

**Issue by tabakerov** [fsprojects/Elmish.XamarinForms#116]
I've just installed dotnet template

`dotnet new -i Elmish.XamarinForms.Templates`

 and run

`dotnet new elmish-forms-app -lang F# -n Xelmish`

Then I opened solution with VS 2017 Community for Mac (VS 7.5.1, macOS Mojave 10.14 beta, dotnet --version = 2.1.300) and it gives me the next error:

```/Users/azazeo/Xamarin/Projects/Xelmish/Xelmish/FSC: Error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'voption`1' (FS0193) (Xelmish)```

**Comment by dsyme** [comment]
There was a glitch in VS for Mac build support related to FSharp.Core, I'm not sure which exact version. I'll check now with the latest stable (VS 7.5.3.7, Mono 5.10.1.57, dotnet 2.1.301)

**Comment by dsyme** [comment]
You're hitting this bug. https://github.com/mono/monodevelop/pull/5137. I'm trialling a workaround

**Comment by dsyme** [comment]
0.13.10

**Comment by dsyme** [comment]
Please reopen if you're still having issues
