### ISSUE TITLE
Swapping page type inside NavigationPage does not work

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Elmish.XamarinForms#148]
When using a NavigationPage, swapping the root ContentPage by another one works and UI is refreshed. (No navigation)
But when swapping to another type (like TabbedPage), UI is not refreshed.
However without a NavigationPage, everything is fine.

Here's a reproduction of the problem:
https://github.com/TimLariviere/EXF_ReproNavPageBug

**Comment by dsyme** [comment]
@TimLariviere I'm not sure, but I wonder if this is a limitation of Xamarin Forms, I recall reading that some kinds of transitions were not possible with changing NavigationPage.

**Comment by TimLariviere** [comment]
@dsyme How exactly is the view changed when using NavigationPage?
Is it entirely removed and then a new NavigationPage is displayed, or does it recycle the NavigationPage, replacing only the root page?

I tried to do the same in a classic C# Xamarin.Forms app.
Replacing the NavigationPage(ContentPage) altogether by a NavigationPage(TabbedPage) works fine.
But recycling the NavPage and replacing the root page won't. (throws an exception if RemovePage is called before PushPage).

EXF recycling would explain why switching a ContentPage by a ContentPage works, but not an other case (exception silenced?)

**Comment by dsyme** [comment]
> @dsyme How exactly is the view changed when using NavigationPage?

The NavigationPage is currently recycled and the Pages are updated through uses of PushAsync and PopAsync in this bespoke code https://github.com/fsprojects/Elmish.XamarinForms/blob/023550ade9c022bf584f2af13101eb8829c2c8c8/Elmish.XamarinForms/ViewConverters.fs#L389

If the NavigationPage is very root element of the App (the thing returned by the overall `view` function) then whether it can be recycled or not depends on `canReuseChild` here: https://github.com/fsprojects/Elmish.XamarinForms/blob/023550ade9c022bf584f2af13101eb8829c2c8c8/Elmish.XamarinForms/ElmishProgram.fs#L86

I think that could be tweaked through a special case rule for NavigationPage?

**Comment by dsyme** [comment]
> (PS: EXF exceptions are always caught? I think re-throwing them and stopping Debug would be better than just tracing them in the console)

There is currently at least one catch-all around individual property update.  

It's tricky: I saw one case of fairly innocuous update causing a failure: bringing down the app seemed harsh if we can assume users look at logging.  Further it seems you sometimes only get good stacks if first-chance exception conditions are used. Not many people know how to turn them on.
