### ISSUE TITLE
Readme's code snippet simplification?

### ISSUE THREAD

**Issue by knocte** [fsprojects/Elmish.XamarinForms#15]
I was reading the code presented in the Readme file and noticed this funcion:

```
    let clockUpdate (msg:ClockMsg) (model:ClockModel) =
        match msg with
        | Tick t -> { model with Time = t }
```

Given that ClockModel is a record type with only one member, then the use of `with` here seems moot. And the model parameter can be unused completely. Wouldn't we want this function to be simplified to...:

```
    let clockUpdate (msg:ClockMsg) =
        match msg with
        | Tick t -> { Time = t }
```

Or am I missing something? Also I don't understand why the `match` block is incomplete.

**Comment by 2sComplement** [comment]
It could be simplified as you wrote, or even further by just having `DateTime` in place of `ClockModel'. It was meant as more of an illustration for view composition, with a sub-model that could be added to if desired. 

> I don't understand why the match block is incomplete

Not sure what you mean by that.

**Comment by knocte** [comment]
>> I don't understand why the match block is incomplete
> Not sure what you mean by that.

This is a complete match block:
```
let foo:Option<int> = Some 1
match foo with
| Some bar -> Baz bar
| None -> ()
```

This is an incomplete match block (which generates a warning):
```
let foo:Option<int> = Some 1
match foo with
| Some bar -> Baz bar
```

**Comment by 2sComplement** [comment]
The match is on type `ClockMsg` which only has one case:
```fsharp
type ClockMsg =
    | Tick of DateTime
```

**Comment by knocte** [comment]
Ah ok I guess I had misread that. I guess, because it's the first time I see a discriminated union with only one case, I thought that wouldn't be possible.

**Comment by dsyme** [comment]
@knocte I adjust the README sample quite a bit, please take a look
