### ISSUE TITLE
Getting Started Project Fails On Compilation: VS For Mac

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Elmish.XamarinForms#166]
I am following the getting started guide and downloaded the  SqueakyApp.   I opened it in Visual Studio for Mac and I am getting the following error:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error MSB4044: The "EmbedMobileProvision" task was not given a value for the required parameter "ProvisioningProfile". (MSB4044) (SqueakyApp.iOS)

I do not have an Apple ID set up on this Mac

**Comment by jamessdixon** [comment]
Note that it does compile when targeting Android and unloading the iOS project.

**Comment by jamessdixon** [comment]
1) Yes, just the simulator deploy
2) Yes, I ran the second step right before reporting the issue
3) .fsproj file is attached - I had to rename so the Mac would allow me to upload it - just change the extension back to .fsproj

Thanks
[SqueakyApp.iOS.docx](https://github.com/fsprojects/Elmish.XamarinForms/files/2334251/SqueakyApp.iOS.docx)

**Comment by TimLariviere** [comment]
This does not seem to be related to the project. Your fsproj is identical to mine.
Tried on another clean Mac as well, no luck reproducing...

Could you share your version info from VS for Mac please?
`Visual Studio [upper left] > About Visual Studio > Show Details > Copy Information`

Also do you have another Mac where you can try to reproduce the issue?

Thanks

**Comment by jamessdixon** [comment]
I deleted the fold and pulled it down again
and now a new problem:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(89,89): Error MSB4057: The target "_DetectSigningIdentity" does not exist in the project. (MSB4057) (SqueakyApp.iOS)
