### ISSUE TITLE
Simplify validation model: eliminate invalid states

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/Elmish.XamarinForms#40]
The state record:
```fs
type Model = 
    { TempF: double
      TempC: double
      Error: string option }
```
works fine for small pages and little components but when your page becomes large (for example when you have a form) having multiple error flags clutters the model and forces the developer to keep the fields values in-sync with their error flags. A better solution in my experience is to encode the value in a single explicit type:
```fs
type Temperature =
   | Value of double 
   | ValidationError of string

type State = 
  { TempF : Temperature
    TempC : Temperature } 
```
this way you can't possibly use the data from `Temperature` if there was a parse/validation error

**Comment by Zaid-Ajaj** [comment]
While we are at the subject, this reminded me of this great article [How Elm Slays a UI Antipattern](http://blog.jenkster.com/2016/06/how-elm-slays-a-ui-antipattern.html) which is about modeling remote data coming from web requests. The idea is to eliminate flags like `IsLoading` and model it as follows:
```fs
type RemoteData<'a> = 
  | Empty // for initial state 
  | Loading 
  | LoadedContent of 'a 
  | LoadError of exn 
```
This greatly simplifies the state. Just putting this out here for samples to come using web services

**Comment by dsyme** [comment]
@Zaid-Ajaj I agree with you. Would you be able to make a PR to the README.md adjusting the text on validation?  The part on remote data could be linked to
