### ISSUE TITLE
How to get started on VS Code

### ISSUE THREAD

**Issue by prashantvc** [fsprojects/Elmish.XamarinForms#42]
The Readme file says to create F# Forms application on [VS Code](https://github.com/fsprojects/Elmish.XamarinForms#getting-started-with-elmishxamarinforms)

Could you elaborate this step? Is it possible to use VS Code at the moment?

**Comment by dsyme** [comment]
@prashantvc You can edit in VS Code but you'll have to run/deploy/debug using Visual Studio
