### ISSUE TITLE
Dynamic Views - Get current value of Entry on Button click

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Elmish.XamarinForms#43]
I'm trying to make a simple form with some fields and a Save button.

Is it possible when clicking the Save button to retrieve the current text of an Entry, without listening to TextChanged and putting the value into the Model?
Doing this means reconstructing all the UI just to update the values available in the button's callback.

**Comment by dsyme** [comment]
I do believe that in the Elmish paradigm the current text would indeed go in the model.   One measure is "If the app were closed and reopened and you want the form entries recovered, the model must contain sufficient information to do this"

> Doing this means reconstructing all the UI just to update the values available in the button's callback.

It does mean not using the UI controls as the place where you save the model of the UI.

**Comment by TimLariviere** [comment]
Ok, it makes sense.
I was fearing that having the original data (single record) + all its pending values in the model would be too much (readability-wise), and make the view blink at each reload.
But after writing it, it seems to work great and code is short.

**Comment by dsyme** [comment]
> I was fearing that having the original data (single record) + all its pending values in the model would be too much (readability-wise)

Yes, I thought so too at first

> and make the view blink at each reload.

If you see "blink when view is updated" problems please report them as issues with a repro.  I think most have these have been ironed out but there will be some problems like this I'm sure (they might in some cases be limitations of XF, or cases where we are not yet good enough in incremental update)
