### ISSUE TITLE
Dynamically changing "ContentPage --> content" property is not updated correctly

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/Elmish.XamarinForms#45]
My demo code is like below

```fsharp
type Msg = Next
type Model = { Count: int }
let init () = { Count = 0 }, Cmd.none
let update msg model =
    match msg with | Next -> { Count = if model.Count > 0 then 0 else 1 }, Cmd.none
let view model dispatch =
    Xaml.ContentPage(
        title = "Demo",
        content =
            if model.Count = 0 then
                Xaml.Button(text = "Next1", command = fun _ -> dispatch Next)
            else
                Xaml.StackLayout(
                    children = [
                        Xaml.Label(text = "Finished")
                        Xaml.Button(text = "Go back", command = fun _ -> dispatch Next) ]
                )
    )
```
When I click next the Count is change to 1 and program is also running in to else block, but the UI is not updated.

**Comment by gibranrosa** [comment]
I think there is some limitation for the ContentPage to handle updates, but with a slight modification to your view it works:
`    let view model dispatch =
        Xaml.ContentPage(
            title = "Demo",
            content =
                Xaml.StackLayout(
                        children = [
                            if model.Count = 0 then
                                yield Xaml.Button(text = "Next1", command = (fun _ -> dispatch Next), textColor = Color.Black)
                            else                    
                                yield Xaml.Label(text = "Finished")
                                yield Xaml.Button(text = "Go back", command = fun _ -> dispatch Next) ]
                            )
                )`

**Comment by dsyme** [comment]
@gibranrosa Do you know if/where that limitation is discussed? I presume that's a limitation of the Xamarin Forms implementation (see here https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ContentPage.cs)

Thanks

**Comment by albertwoo** [comment]
Thanks for the explanation. But if there is some way to solve this limitation then it will save a lot of time for beginners like me.

I will close this then.

**Comment by dsyme** [comment]
@albertwoo I'll keep it open with a different title as it is a definite glitch, though it's likely a limitation in Xamarin.Forms

**Comment by albertwoo** [comment]
@gibranrosa great job! I was planning to investigate this today, now my life is saved 👍
