### ISSUE TITLE
[Discussion] This works with Xamarin.Forms.WinForms (by aosoft), yes, a WinForms implementation!

### ISSUE THREAD

**Issue by gibranrosa** [fsprojects/Elmish.XamarinForms#49]
Just to report that I was able to make it work with https://github.com/aosoft/Xamarin.Forms.WinForms, a WinForms implementation of Xamarin.Forms!

It already works with the Nuget release, but I have made 2 PRs, 1 accepted, to the repo, so I recompile, and that is the gist showing the necessary to make it work: 

https://gist.github.com/gibranrosa/6bc75fdc0ccb787f51fa726a64246047

One note: There is some Big file names in the library, so I could compile it only putting it in the root dir.

**Comment by dsyme** [comment]
This is covered by #55
