### ISSUE TITLE
Xaml.Label --> XF.Label or Forms.Label or View.Label or UI.Label

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Elmish.XamarinForms#50]
Feedback from @migueldeicaza and others: 

> rename `Xaml.FooBar` to something else, e.g. `UI.FooBar` or `XF.FooBar` or `Forms.FooBar`

Of these I think I would prefer `XF.Label`, `XF.Button` etc., but please chime in if you have a preference.

**Comment by dsyme** [comment]
Example code sample:
```fsharp
let view model dispatch =
    ...
    dependsOn () (fun model () -> 
        XF.StackLayout(
          children=
            [ XF.Label(text=sprintf "Grid (6x6, auto):")
              XF.Grid(rowdefs= [for i in 1 .. 6 -> box "auto"],
                        coldefs=[for i in 1 .. 6 -> box "auto"], 
                        children = [ for i in 1 .. 6 do for j in 1 .. 6 -> 
                                       Xaml.BoxView(Color((1.0/float i), (1.0/float j), (1.0/float (i+j)), 1.0) )
                                              .GridRow(i-1).GridColumn(j-1) ] )
            ])
```

**Comment by dsyme** [comment]
Note that implementing the C# 5.0 "open static classes" feature in F# would allow  th prefix to be dropped altogether, but right now we need a qualifier.

**Comment by nosami** [comment]
I was going to suggest a rename too as it's not XAML! :+1: for `XF`

**Comment by aloisdeniel** [comment]
I prefer 'Forms' since it is consistent with 'Xamarin.Forms'. And I hate accronyms... :)

**Comment by charlesroddie** [comment]
I am trying to figure out the purpose of `XF` (if that is what it will be called). I have not used Elmish approaches so please correct me if I am wrong about any of the following.

1. Elmish is about defining the view as a pure function of an immutable model type and an update type, and attempting to do this efficiently, without unnecessarily recreating views. This library provides helper functions for this purpose, such as `dependsOn`.

2. `XF` seems to be a model of Xamarin.Forms. This enormous task is carried out in DynamicXaml.fs, which attempts to maintain order in a large untyped system.

### If 2 is necessary for 1 then
the Elmish approach has serious problems. You will have to maintain an very large and hazardous library DynamicXaml.fs , update it whenever Xamarin.Forms changes, and it will only apply to one UI framework, and only to stock controls and not user-defined controls and properties.

### else
2 should be removed. We are then left with a separated out Elmish approach that works for any .Net UI framework.

**Comment by dsyme** [comment]
Hi @charlesroddie 

Yes, 2 is necessary for 1.  

> This enormous task is carried out in DynamicXaml.fs

The code is generated from the model in `bindings.json` and the `binding.json` is fairly straight-forward. 

Regarding size - I've added to the roadmap to double check that the Xamarin tree-shaker removes unused portions of the code and only leaves the update code for the controls you use.  If it doesn't there's something wrong with the tree-shaker, since there are no circular dependencies.

> which attempts to maintain order in a large type-unsafe system. 

TBH it's actually fairly buttoned down.  The process of code generation from bindings,json and subsequent compilation checks the overall validity of the construction of DynamicXaml.fs.  There are niggles but the approach is sound in the sense that if properties are missing or the bindings.json model is ill-typed then you find out during the construction of the library.  I've not encountered any practical typing problems from this approach.

> You will have to maintain DynamicXaml.fs 

You currently need to maintain bindings.json, and yes, there is a question of versioning and delivery. 

For 3rd party controls there are various ways to skin this cat and we haven't started skinning yet (as noted in the README.md). The approach closest to the results you want would be to make an F# type provider that automates the process. You would point the TP at any set of normal-looking control libraries (i.e. controls whose API surface area looks like the ones in Xamarin.Forms.Core.dll) and do the appropriate thing.  An optional `bindings.json` could be used to configure this. The code would look something like this

```
type XF = XamlBindings<"Xamarin.Forms.Core; Xamarin.Forms.Maps; WidgetsInc.Widgets">

... code as before ...
```

In theory this approach could remove the need for any base `Elmish.XamarinForms.dll` library and all necessary code would be injected into the user application. This removes versioning problems but comes with some other drawbacks.

>  it will only apply to one UI framework

The approach is being prototyped over Xamarin.Forms but can in theory be applied to WPF and UWP directly.  That's a separate story though. XF is a sensible place to start. The approach is fairly straight-forward so it's likely we'll see other variations on it.

**Comment by ReedCopsey** [comment]
> The approach is being prototyped over Xamarin.Forms but can in theory be applied to WPF and UWP directly. That's a separate story though. XF is a sensible place to start

This is a great argument for XF.Label vs Xaml.* right here. You refer to it as XF, but use Xaml, which will only cause confusion as this is ported to other platforms.

Ideally, the core for this could he shared eventually.

**Comment by charlesroddie** [comment]
@dsyme Thanks for the explanations. I am interested in this approach and promised once to do a blog post on different methods for F# UIs... when I can find some time.

> You would point the TP at any set of normal-looking control libraries (i.e. controls whose API surface area looks like the ones in Xamarin.Forms.Core.dll) and do the appropriate thing.

That would be really impressive. I'm surprised that is even possible.

**Comment by dsyme** [comment]
> > You would point the TP at any set of normal-looking control libraries (i.e. controls whose API surface area looks like the ones in Xamarin.Forms.Core.dll) and do the appropriate thing.

> That would be really impressive. I'm surprised it is even possible.

It's not clear it is without too much manual tweaking. Let's say it's an aspiration right now...

**Comment by dsyme** [comment]
@charlesroddie Re performance:  My gut feeling is that the perf of the full emish approach (with appropriate use of `dependsOn`) will be adequate for many scenarios. However I am assuming that we will eventually need to document a number of "hacks" that can be used to code hot paths, e.g.
* hacks that allow the direct use of mutable data and ObservableCollection in the model
* hacks that allow direct access to the mutable UI components in the underlying XF tree.

Use of these would presumably be seen as "a necessary evil" in the same way as `mutable` is often seen in other F# programming.

**Comment by dsyme** [comment]
@charlesroddie Using 3rd party controls by writing a bit of maual code is now documented here: https://fsprojects.github.io/Elmish.XamarinForms/views-extending.html.  This is not automated

**Comment by dsyme** [comment]
We now use `View.Label` etc., see #118
