### ISSUE TITLE
API confusion

### ISSUE THREAD

**Issue by bugQ** [fsprojects/Elmish.XamarinForms#67]
I'm trying to adapt one of the samples into a reusable template for new projects.  My difficulty is that the master branch is currently API-incompatible with the NuGet package currently available, version 0.4.4, specifically because the property ProgramRunner.Model was replaced by an immutable property and a setter method as part of the commit titled "reduce size of generated code" (011cb1fa).  I realize that Elmish.XamarinForms is still in an early stage and that the API is still volatile, but I have two questions:

1. My understanding of the CLR doesn't quite explain how the API change improves things.  Was reducing the size of the bytecode the true reason, and if so, could I ask how (for my own benefit)?
2. Which commit was version 0.4.4 (and could it perhaps be publicly tagged), so that I might make a template based on the current NuGet package?

**Comment by dsyme** [comment]
I agree the API isn't substantially better (though not particularly worse either)

In any case package 0.5.0 is now pushed, thanks!
