### ISSUE TITLE
Navigation composition breaks samples

### ISSUE THREAD

**Issue by jakzale** [fsprojects/Elmish.XamarinForms#8]
Very nice piece of work.  Played around with the CounterApp sample and noticed that it is currently broken.

CounterApp throws an invalid operation exception when setting up the binding context for the page.([Combinators.fs:187](https://github.com/fsprojects/Elmish.XamarinForms/blob/d23452a9a0b4da5b51e7dc70aee94ce764bd4a01/Elmish.XamarinForms/Combinators.fs#L187))

It looks up the page's name ,`"Page"`, in the ViewModels `props`, which will fail.

In the end I got the sample to work, but I do not have a good solution for that, as the `props` on the ViewModel do not seem to be aware of application pages.

Have you considered parameterising the constructor of ViewModel over the list of pages?

**Comment by dsyme** [comment]
@jakzale Sorry not for answering sooner.  I just checked and the CounterApp samples seems to work ok, at least on Android (on device).  Perhaps I fixed this?
