### ISSUE TITLE
search bar command

### ISSUE THREAD

**Issue by poborin** [fsprojects/Elmish.XamarinForms#81]
First of all, I want to say thank you @dsyme for such an amazing project!

Here is a question:
How can I use the SearchBar control? I found that there are no arguments in the searchComannd, and textChanged event is not implemented. How can use value of the searchBar then?

**Comment by dsyme** [comment]
@poborin This needs to be completed and a sample added in AllControls.  If you'd like to take a crack at it see bindings.json and the DEVGUIDE.md, otherwise I'll add it tomorrow in 0.8.0, thanks

**Comment by poborin** [comment]
let me see what I can do tonight. I'd love to try

**Comment by dsyme** [comment]
@poborin Sorry... Already done it... It's in #80

**Comment by dsyme** [comment]
@poborin Could you take it for a spin?  See https://github.com/fsprojects/Elmish.XamarinForms/pull/80/files#diff-1b3c855fd366f468caf9e1f4889fb712R421

The nuget has already been pushed, 0.8.0

**Comment by dsyme** [comment]
@poborin I know we do need docs for SearchBar under docs/elements.md... :)

**Comment by poborin** [comment]
perfect!
I have added a pull request #84 
so, I guess we can close an issue
